train_file: ['/home/monajati/main/med/blip/med_data/medical_20k_75per.json'
             ]            
laion_path: ''   
checkpoint: '/home/monajati/main/med/blip/model_base.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 10

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 3e-5
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 60
warmup_steps: 300



